name: natron
base: core24
adopt-info: natron
summary: Natron
description: |
  Open-source compositing software. Node-graph based. Similar in
  functionalities to Adobe After Effects and Nuke by The Foundry.
compression: lzo
grade: stable
confinement: strict

platforms:
  amd64:

parts:
  build-trigger:
    plugin: nil
    source: https://github.com/NatronGitHub/Natron.git
  natron:
    plugin: nil
    override-build: |
      set -xeu
      echo "Get GitHub releases..."
      wget --quiet https://api.github.com/repos/NatronGitHub/Natron/releases -O releases.json
      VERSION=$(jq . releases.json | grep tag_name | grep -v rc1 | grep -v alpha | head -n 1 | cut -d'"' -f4 | tr -d "v")
      TAR_URL=$(grep browser_download_url releases.json | grep "${VERSION}" | grep tar.xz | grep Linux-x86_64-no-installer | cut -d'"' -f4)
      wget --quiet $TAR_URL -O natron.tar.xz
      unxz natron.tar.xz
      tar xvf natron.tar --strip-components=1 -C $CRAFT_PART_INSTALL/
      rm natron.tar releases.json
      craftctl set version="$VERSION"
    build-packages:
      - wget
      - jq
      - xz-utils
    stage-packages:
      - libbsd0
      - libgomp1
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libice6
      - libsm6
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libgl1-mesa-dri
      - libasound2t64

apps:
  natron:
    extensions: [ gnome ]
    command: Natron
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - network
