name: natron
base: core24
adopt-info: natron
summary: Natron
description: |
  Open-source compositing software. Node-graph based. Similar in
  functionalities to Adobe After Effects and Nuke by The Foundry.
compression: lzo
grade: stable
confinement: strict

platforms:
  amd64:

parts:
  build-trigger:
    plugin: nil
    source: https://github.com/NatronGitHub/Natron.git
  natron:
    plugin: nil
    override-build: |
      set -xeu
      echo "Get GitHub latest release..."
      RELEASE=$(curl -sL https://api.github.com/repos/NatronGitHub/Natron/releases/latest)
      VERSION=$(echo "$RELEASE" | jq -r '.tag_name' | tr -d 'v')
      TAR_URL=$(echo "$RELEASE" | jq -r '.assets[] | select(.name | test("Linux-x86_64-no-installer\\.tar\\.xz$")) | .browser_download_url')
      echo "Downloading Natron $VERSION from $TAR_URL"
      wget --quiet "$TAR_URL" -O natron.tar.xz
      unxz natron.tar.xz
      tar xvf natron.tar --strip-components=1 -C $CRAFT_PART_INSTALL/
      rm natron.tar
      craftctl set version="$VERSION"
    build-packages:
      - curl
      - wget
      - jq
      - xz-utils
    stage-packages:
      - libbsd0
      - libgomp1
      - libgl1
      - libglu1-mesa
      - libglvnd0
      - libglx0
      - libice6
      - libsm6
      - libx11-6
      - libxau6
      - libxcb1
      - libxcursor1
      - libxdmcp6
      - libxext6
      - libxfixes3
      - libxi6
      - libxinerama1
      - libxrandr2
      - libxrender1
      - libgl1-mesa-dri
      - libasound2t64

apps:
  natron:
    extensions: [ gnome ]
    command: Natron
    plugs:
      - home
      - removable-media
      - desktop
      - desktop-legacy
      - x11
      - opengl
      - network
